package com.mrburgerus.ImmersiveArms.render.model;

import com.mrburgerus.ImmersiveArms.item.items.ItemSniperRifle;
import com.mrburgerus.ImmersiveArms.item.items.ItemWeapon;
import net.minecraft.client.model.ModelBase;
import net.minecraft.client.model.ModelRenderer;
import net.minecraft.entity.Entity;

public class ModelSniperRifle extends ModelBase
{
  //fields
    public ModelRenderer Barrel;
    public ModelRenderer Brake;
    public ModelRenderer FrontSight;
    public ModelRenderer BarrelBack;
    public ModelRenderer BodyFront;
    public ModelRenderer Rib;
    public ModelRenderer BodyReciever;
    public ModelRenderer Reciever2;
    public ModelRenderer BodyInter;
    public ModelRenderer RibBack;
    public ModelRenderer BottomRib;
    public ModelRenderer BoltCut1;
    public ModelRenderer BoltCut2;
    public ModelRenderer BoltCut3;
    public ModelRenderer RibBolt;
    public ModelRenderer Magazine;
    public ModelRenderer MagCatch;
    public ModelRenderer Grip;
    public ModelRenderer MagHold;
    public ModelRenderer Guard;
    public ModelRenderer StockStem;
    public ModelRenderer Stock1;
    public ModelRenderer Stock2;
    public ModelRenderer ScopeMBack;
    public ModelRenderer ScopeMFront;
    public ModelRenderer ScopeTube;
    public ModelRenderer EyePiece;
    public ModelRenderer ScopeFront;
    public ModelRenderer BulletBolt;
  
  public ModelSniperRifle()
  {
    textureWidth = 64;
    textureHeight = 32;
    
      Barrel = new ModelRenderer(this, 0, 30);
      Barrel.addBox(0F, 0F, 0F, 20, 1, 1);
      Barrel.setRotationPoint(0F, 0F, 0F);
      Barrel.setTextureSize(64, 32);
      Barrel.mirror = true;
      setRotation(Barrel, 0F, 0F, 0F);
      Brake = new ModelRenderer(this, 0, 25);
      Brake.addBox(17F, -0.5F, -0.5F, 6, 2, 2);
      Brake.setRotationPoint(0F, 0F, 0F);
      Brake.setTextureSize(64, 32);
      Brake.mirror = true;
      setRotation(Brake, 0F, 0F, 0F);
      FrontSight = new ModelRenderer(this, 2, 25);
      FrontSight.addBox(20F, -0.9F, 0F, 2, 1, 1);
      FrontSight.setRotationPoint(0F, 0F, 0F);
      FrontSight.setTextureSize(64, 32);
      FrontSight.mirror = true;
      setRotation(FrontSight, 0F, 0F, 0F);
      BarrelBack = new ModelRenderer(this, 42, 28);
      BarrelBack.addBox(-3F, 0F, 0F, 3, 2, 2);
      BarrelBack.setRotationPoint(0F, -0.5F, -0.5F);
      BarrelBack.setTextureSize(64, 32);
      BarrelBack.mirror = true;
      setRotation(BarrelBack, 0F, 0F, 0F);
      BodyFront = new ModelRenderer(this, 0, 18);
      BodyFront.addBox(-12F, -1.5F, -1F, 9, 3, 3);
      BodyFront.setRotationPoint(0F, 0F, 0F);
      BodyFront.setTextureSize(64, 32);
      BodyFront.mirror = true;
      setRotation(BodyFront, 0F, 0F, 0F);
      Rib = new ModelRenderer(this, 0, 21);
      Rib.addBox(-12F, -2F, -0.5F, 13, 1, 2);
      Rib.setRotationPoint(0F, 0F, 0F);
      Rib.setTextureSize(64, 32);
      Rib.mirror = true;
      setRotation(Rib, 0F, 0F, 0F);
      BodyReciever = new ModelRenderer(this, 0, 19);
      BodyReciever.addBox(-18F, -0.5F, -1F, 6, 2, 3);
      BodyReciever.setRotationPoint(0F, 0F, 0F);
      BodyReciever.setTextureSize(64, 32);
      BodyReciever.mirror = true;
      setRotation(BodyReciever, 0F, 0F, 0F);
      Reciever2 = new ModelRenderer(this, 0, 20);
      Reciever2.addBox(-18F, -2F, 0F, 6, 2, 2);
      Reciever2.setRotationPoint(0F, 0F, 0F);
      Reciever2.setTextureSize(64, 32);
      Reciever2.mirror = true;
      setRotation(Reciever2, 0F, 0F, 0F);
      BodyInter = new ModelRenderer(this, 0, 18);
      BodyInter.addBox(-19F, -1.5F, -1F, 1, 3, 3);
      BodyInter.setRotationPoint(0F, 0F, 0F);
      BodyInter.setTextureSize(64, 32);
      BodyInter.mirror = true;
      setRotation(BodyInter, 0F, 0F, 0F);
      RibBack = new ModelRenderer(this, 0, 21);
      RibBack.addBox(-19F, -2F, -0.5F, 1, 1, 2);
      RibBack.setRotationPoint(0F, 0F, 0F);
      RibBack.setTextureSize(64, 32);
      RibBack.mirror = true;
      setRotation(RibBack, 0F, 0F, 0F);
      BottomRib = new ModelRenderer(this, 0, 14);
      BottomRib.addBox(-20F, 0.7F, -0.5F, 18, 1, 2);
      BottomRib.setRotationPoint(0F, 0F, 0F);
      BottomRib.setTextureSize(64, 32);
      BottomRib.mirror = true;
      setRotation(BottomRib, 0F, 0F, 0F);
      BoltCut1 = new ModelRenderer(this, 0, 20);
      BoltCut1.addBox(-20F, 0.5F, -1F, 1, 1, 3);
      BoltCut1.setRotationPoint(0F, 0F, 0F);
      BoltCut1.setTextureSize(64, 32);
      BoltCut1.mirror = true;
      setRotation(BoltCut1, 0F, 0F, 0F);
      BoltCut2 = new ModelRenderer(this, 0, 21);
      BoltCut2.addBox(-20F, -1.5F, 1F, 1, 2, 1);
      BoltCut2.setRotationPoint(0F, 0F, 0F);
      BoltCut2.setTextureSize(64, 32);
      BoltCut2.mirror = true;
      setRotation(BoltCut2, 0F, 0F, 0F);
      BoltCut3 = new ModelRenderer(this, 0, 18);
      BoltCut3.addBox(-21F, -1.5F, -1F, 1, 3, 3);
      BoltCut3.setRotationPoint(0F, 0F, 0F);
      BoltCut3.setTextureSize(64, 32);
      BoltCut3.mirror = true;
      setRotation(BoltCut3, 0F, 0F, 0F);
      RibBolt = new ModelRenderer(this, 0, 21);
      RibBolt.addBox(-21F, -2F, -0.5F, 1, 1, 2);
      RibBolt.setRotationPoint(0F, 0F, 0F);
      RibBolt.setTextureSize(64, 32);
      RibBolt.mirror = true;
      setRotation(RibBolt, 0F, 0F, 0F);
      Magazine = new ModelRenderer(this, 50, 0);
      Magazine.addBox(-18F, 0F, 0F, 6, 4, 1);
      Magazine.setRotationPoint(0F, 0F, 0F);
      Magazine.setTextureSize(64, 32);
      Magazine.mirror = true;
      setRotation(Magazine, 0F, 0F, -0.0174533F);
      MagCatch = new ModelRenderer(this, 0, 14);
      MagCatch.addBox(-13F, 1F, -0.5F, 2, 1, 2);
      MagCatch.setRotationPoint(0F, 0F, 0F);
      MagCatch.setTextureSize(64, 32);
      MagCatch.mirror = true;
      setRotation(MagCatch, 0F, 0F, 0F);
      Grip = new ModelRenderer(this, 43, 0);
      Grip.addBox(-21F, 4F, 0F, 2, 4, 1);
      Grip.setRotationPoint(0F, 0F, 0F);
      Grip.setTextureSize(64, 32);
      Grip.mirror = true;
      setRotation(Grip, 0F, 0F, 0.1487144F);
      MagHold = new ModelRenderer(this, 0, 13);
      MagHold.addBox(-18.5F, 1F, -0.5F, 1, 2, 2);
      MagHold.setRotationPoint(0F, 0F, 0F);
      MagHold.setTextureSize(64, 32);
      MagHold.mirror = true;
      setRotation(MagHold, 0F, 0F, 0F);
      Guard = new ModelRenderer(this, 0, 13);
      Guard.addBox(-20F, 3F, 0F, 2, 0, 1);
      Guard.setRotationPoint(0F, 0F, 0F);
      Guard.setTextureSize(64, 32);
      Guard.mirror = true;
      setRotation(Guard, 0F, 0F, 0F);
      StockStem = new ModelRenderer(this, 0, 22);
      StockStem.addBox(-26F, 0F, 0F, 5, 1, 1);
      StockStem.setRotationPoint(0F, 0F, 0F);
      StockStem.setTextureSize(64, 32);
      StockStem.mirror = true;
      setRotation(StockStem, 0F, 0F, 0F);
      Stock1 = new ModelRenderer(this, 52, 26);
      Stock1.addBox(-33F, -1F, -0.5F, 4, 4, 2);
      Stock1.setRotationPoint(0F, 0F, 0F);
      Stock1.setTextureSize(64, 32);
      Stock1.mirror = true;
      setRotation(Stock1, 0F, 0F, 0F);
      Stock2 = new ModelRenderer(this, 52, 21);
      Stock2.addBox(-29F, -0.5F, -0.5F, 4, 3, 2);
      Stock2.setRotationPoint(0F, 0F, 0F);
      Stock2.setTextureSize(64, 32);
      Stock2.mirror = true;
      setRotation(Stock2, 0F, 0F, 0F);
      ScopeMBack = new ModelRenderer(this, 0, 20);
      ScopeMBack.addBox(-15F, -4.5F, 0F, 1, 3, 1);
      ScopeMBack.setRotationPoint(0F, 0F, 0F);
      ScopeMBack.setTextureSize(64, 32);
      ScopeMBack.mirror = true;
      setRotation(ScopeMBack, 0F, 0F, 0F);
      ScopeMFront = new ModelRenderer(this, 0, 19);
      ScopeMFront.addBox(-9F, -4.5F, -0.5F, 1, 3, 2);
      ScopeMFront.setRotationPoint(0F, 0F, 0F);
      ScopeMFront.setTextureSize(64, 32);
      ScopeMFront.mirror = true;
      setRotation(ScopeMFront, 0F, 0F, 0F);
      ScopeTube = new ModelRenderer(this, 0, 9);
      ScopeTube.addBox(-17F, -4F, 0F, 11, 1, 1);
      ScopeTube.setRotationPoint(0F, 0F, 0F);
      ScopeTube.setTextureSize(64, 32);
      ScopeTube.mirror = true;
      setRotation(ScopeTube, 0F, 0F, 0F);
      EyePiece = new ModelRenderer(this, 0, 4);
      EyePiece.addBox(-18.5F, -4.5F, -0.5F, 2, 2, 2);
      EyePiece.setRotationPoint(0F, 0F, 0F);
      EyePiece.setTextureSize(64, 32);
      EyePiece.mirror = true;
      setRotation(EyePiece, 0F, 0F, 0F);
      ScopeFront = new ModelRenderer(this, 0, 0);
      ScopeFront.addBox(-7.5F, -4.5F, -0.5F, 5, 2, 2);
      ScopeFront.setRotationPoint(0F, 0F, 0F);
      ScopeFront.setTextureSize(64, 32);
      ScopeFront.mirror = true;
      setRotation(ScopeFront, 0F, 0F, 0F);
      BulletBolt = new ModelRenderer(this, 24, 0);
      BulletBolt.addBox(-18F, -1.5F, -0.5F, 6, 1, 1);
      BulletBolt.setRotationPoint(0F, 0F, 0F);
      BulletBolt.setTextureSize(64, 32);
      BulletBolt.mirror = true;
      setRotation(BulletBolt, 0F, 0F, 0F);
  }
  
  public void render(Entity entity, float f, float f1, float f2, float f3, float f4, float f5)
  {
    super.render(entity, f, f1, f2, f3, f4, f5);
    setRotationAngles(f, f1, f2, f3, f4, f5, entity);
    Barrel.render(f5);
    Brake.render(f5);
    FrontSight.render(f5);
    BarrelBack.render(f5);
    BodyFront.render(f5);
    Rib.render(f5);
    BodyReciever.render(f5);
    Reciever2.render(f5);
    BodyInter.render(f5);
    RibBack.render(f5);
    BottomRib.render(f5);
    BoltCut1.render(f5);
    BoltCut2.render(f5);
    BoltCut3.render(f5);
    RibBolt.render(f5);
    Magazine.render(f5);
    MagCatch.render(f5);
    Grip.render(f5);
    MagHold.render(f5);
    Guard.render(f5);
    StockStem.render(f5);
    Stock1.render(f5);
    Stock2.render(f5);
    ScopeMBack.render(f5);
    ScopeMFront.render(f5);
    ScopeTube.render(f5);
    EyePiece.render(f5);
    ScopeFront.render(f5);
    BulletBolt.render(f5);
  }
    public void renderModel(float f5)
    {
        Barrel.render(f5);
        Brake.render(f5);
        FrontSight.render(f5);
        BarrelBack.render(f5);
        BodyFront.render(f5);
        Rib.render(f5);
        BodyReciever.render(f5);
        Reciever2.render(f5);
        BodyInter.render(f5);
        RibBack.render(f5);
        BottomRib.render(f5);
        BoltCut1.render(f5);
        BoltCut2.render(f5);
        BoltCut3.render(f5);
        RibBolt.render(f5);
        Magazine.render(f5);
        MagCatch.render(f5);
        Grip.render(f5);
        MagHold.render(f5);
        Guard.render(f5);
        StockStem.render(f5);
        Stock1.render(f5);
        Stock2.render(f5);
        ScopeMBack.render(f5);
        ScopeMFront.render(f5);
        ScopeTube.render(f5);
        EyePiece.render(f5);
        ScopeFront.render(f5);
        BulletBolt.render(f5);
    }

    public void renderModelnoBrake(float f5)
    {
        Barrel.render(f5);
        BarrelBack.render(f5);
        BodyFront.render(f5);
        Rib.render(f5);
        BodyReciever.render(f5);
        Reciever2.render(f5);
        BodyInter.render(f5);
        RibBack.render(f5);
        BottomRib.render(f5);
        BoltCut1.render(f5);
        BoltCut2.render(f5);
        BoltCut3.render(f5);
        RibBolt.render(f5);
        Magazine.render(f5);
        MagCatch.render(f5);
        Grip.render(f5);
        MagHold.render(f5);
        Guard.render(f5);
        StockStem.render(f5);
        Stock1.render(f5);
        Stock2.render(f5);
        ScopeMBack.render(f5);
        ScopeMFront.render(f5);
        ScopeTube.render(f5);
        EyePiece.render(f5);
        ScopeFront.render(f5);
        BulletBolt.render(f5);
    }


    private void setRotation(ModelRenderer model, float x, float y, float z)
  {
    model.rotateAngleX = x;
    model.rotateAngleY = y;
    model.rotateAngleZ = z;
  }
    public void setRotationAngles(float f, float f1, float f2, float f3, float f4, float f5, Entity entity) {
        super.setRotationAngles(f, f1, f2, f3, f4, f5, entity);
    }

}
